using System;
using System.Collections.Generic;

namespace DataAccessLayer.SAPHandler.SqlHandler.Models
{
    public partial class JDT1
    {
        public int TransId { get; set; }
        public int Line_ID { get; set; }
        public string Account { get; set; }
        public decimal? Debit { get; set; }
        public decimal? Credit { get; set; }
        public decimal? SYSCred { get; set; }
        public decimal? SYSDeb { get; set; }
        public decimal? FCDebit { get; set; }
        public decimal? FCCredit { get; set; }
        public string FCCurrency { get; set; }
        public DateTime? DueDate { get; set; }
        public int? SourceID { get; set; }
        public short? SourceLine { get; set; }
        public string ShortName { get; set; }
        public int? IntrnMatch { get; set; }
        public int? ExtrMatch { get; set; }
        public string ContraAct { get; set; }
        public string LineMemo { get; set; }
        public string Ref3Line { get; set; }
        public string TransType { get; set; }
        public DateTime? RefDate { get; set; }
        public DateTime? Ref2Date { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public int? CreatedBy { get; set; }
        public string BaseRef { get; set; }
        public string Project { get; set; }
        public string TransCode { get; set; }
        public string ProfitCode { get; set; }
        public DateTime? TaxDate { get; set; }
        public decimal? SystemRate { get; set; }
        public DateTime? MthDate { get; set; }
        public decimal? ToMthSum { get; set; }
        public short? UserSign { get; set; }
        public int? BatchNum { get; set; }
        public int? FinncPriod { get; set; }
        public int? RelTransId { get; set; }
        public int? RelLineID { get; set; }
        public string RelType { get; set; }
        public int? LogInstanc { get; set; }
        public string VatGroup { get; set; }
        public decimal? BaseSum { get; set; }
        public decimal? VatRate { get; set; }
        public string Indicator { get; set; }
        public string AdjTran { get; set; }
        public string RevSource { get; set; }
        public string ObjType { get; set; }
        public DateTime? VatDate { get; set; }
        public string PaymentRef { get; set; }
        public decimal? SYSBaseSum { get; set; }
        public int? MultMatch { get; set; }
        public string VatLine { get; set; }
        public decimal? VatAmount { get; set; }
        public decimal? SYSVatSum { get; set; }
        public string Closed { get; set; }
        public decimal? GrossValue { get; set; }
        public int? CheckAbs { get; set; }
        public int? LineType { get; set; }
        public string DebCred { get; set; }
        public int? SequenceNr { get; set; }
        public string StornoAcc { get; set; }
        public decimal? BalDueDeb { get; set; }
        public decimal? BalDueCred { get; set; }
        public decimal? BalFcDeb { get; set; }
        public decimal? BalFcCred { get; set; }
        public decimal? BalScDeb { get; set; }
        public decimal? BalScCred { get; set; }
        public string IsNet { get; set; }
        public string DunWizBlck { get; set; }
        public int? DunnLevel { get; set; }
        public DateTime? DunDate { get; set; }
        public short? TaxType { get; set; }
        public string TaxPostAcc { get; set; }
        public string StaCode { get; set; }
        public int? StaType { get; set; }
        public string TaxCode { get; set; }
        public DateTime? ValidFrom { get; set; }
        public decimal? GrossValFc { get; set; }
        public DateTime? LvlUpdDate { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public int? MIEntry { get; set; }
        public int? MIVEntry { get; set; }
        public int? ClsInTP { get; set; }
        public int? CenVatCom { get; set; }
        public int? MatType { get; set; }
        public int? PstngType { get; set; }
        public DateTime? ValidFrom2 { get; set; }
        public DateTime? ValidFrom3 { get; set; }
        public DateTime? ValidFrom4 { get; set; }
        public DateTime? ValidFrom5 { get; set; }
        public int? Location { get; set; }
        public string WTaxCode { get; set; }
        public decimal? EquVatRate { get; set; }
        public decimal? EquVatSum { get; set; }
        public decimal? SYSEquSum { get; set; }
        public decimal? TotalVat { get; set; }
        public decimal? SYSTVat { get; set; }
        public string WTLiable { get; set; }
        public string WTLine { get; set; }
        public decimal? WTApplied { get; set; }
        public decimal? WTAppliedS { get; set; }
        public decimal? WTAppliedF { get; set; }
        public decimal? WTSum { get; set; }
        public decimal? WTSumFC { get; set; }
        public decimal? WTSumSC { get; set; }
        public string PayBlock { get; set; }
        public int? PayBlckRef { get; set; }
        public string LicTradNum { get; set; }
        public int? InterimTyp { get; set; }
        public int? DprId { get; set; }
        public string MatchRef { get; set; }
        public string Ordered { get; set; }
        public int? CUP { get; set; }
        public int? CIG { get; set; }
        public int? BPLId { get; set; }
        public string BPLName { get; set; }
        public string VatRegNum { get; set; }
        public string SLEDGERF { get; set; }
        public string InitRef2 { get; set; }
        public string InitRef3Ln { get; set; }
        public string ExpUUID { get; set; }
        public string ExpOPType { get; set; }
        public int? ExTransId { get; set; }
        public short? DocArr { get; set; }
        public int? DocLine { get; set; }
        public string MYFtype { get; set; }
        public string U_B1SYS_WHT { get; set; }
    }
}
