using System;
using System.Collections.Generic;

namespace DataAccessLayer.SAPHandler.SqlHandler.Models
{
    public partial class OHEM
    {
        public int empID { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string sex { get; set; }
        public string jobTitle { get; set; }
        public int? type { get; set; }
        public short? dept { get; set; }
        public short? branch { get; set; }
        public string workStreet { get; set; }
        public string workBlock { get; set; }
        public string workZip { get; set; }
        public string workCity { get; set; }
        public string workCounty { get; set; }
        public string workCountr { get; set; }
        public string workState { get; set; }
        public int? manager { get; set; }
        public int? userId { get; set; }
        public int? salesPrson { get; set; }
        public string officeTel { get; set; }
        public string officeExt { get; set; }
        public string mobile { get; set; }
        public string pager { get; set; }
        public string homeTel { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public DateTime? startDate { get; set; }
        public int? status { get; set; }
        public decimal? salary { get; set; }
        public string salaryUnit { get; set; }
        public decimal? emplCost { get; set; }
        public string empCostUnt { get; set; }
        public DateTime? termDate { get; set; }
        public int? termReason { get; set; }
        public string bankCode { get; set; }
        public string bankBranch { get; set; }
        public string bankBranNo { get; set; }
        public string bankAcount { get; set; }
        public string homeStreet { get; set; }
        public string homeBlock { get; set; }
        public string homeZip { get; set; }
        public string homeCity { get; set; }
        public string homeCounty { get; set; }
        public string homeCountr { get; set; }
        public string homeState { get; set; }
        public DateTime? birthDate { get; set; }
        public string brthCountr { get; set; }
        public string martStatus { get; set; }
        public short? nChildren { get; set; }
        public string govID { get; set; }
        public string citizenshp { get; set; }
        public string passportNo { get; set; }
        public DateTime? passportEx { get; set; }
        public string picture { get; set; }
        public string remark { get; set; }
        public string attachment { get; set; }
        public string salaryCurr { get; set; }
        public string empCostCur { get; set; }
        public string WorkBuild { get; set; }
        public string HomeBuild { get; set; }
        public int? position { get; set; }
        public int? AtcEntry { get; set; }
        public string AddrTypeW { get; set; }
        public string AddrTypeH { get; set; }
        public string StreetNoW { get; set; }
        public string StreetNoH { get; set; }
        public string DispMidNam { get; set; }
        public string NamePos { get; set; }
        public string DispComma { get; set; }
        public string CostCenter { get; set; }
        public string CompanyNum { get; set; }
        public int? VacPreYear { get; set; }
        public int? VacCurYear { get; set; }
        public string MunKey { get; set; }
        public string TaxClass { get; set; }
        public string InTaxLiabi { get; set; }
        public string EmTaxCCode { get; set; }
        public string RelPartner { get; set; }
        public decimal? ExemptAmnt { get; set; }
        public string ExemptUnit { get; set; }
        public decimal? AddiAmnt { get; set; }
        public string AddiUnit { get; set; }
        public string TaxOName { get; set; }
        public string TaxONum { get; set; }
        public string HeaInsName { get; set; }
        public string HeaInsCode { get; set; }
        public string HeaInsType { get; set; }
        public string SInsurNum { get; set; }
        public string StatusOfP { get; set; }
        public string StatusOfE { get; set; }
        public string BCodeDateV { get; set; }
        public string DevBAOwner { get; set; }
        public string FNameSP { get; set; }
        public string SurnameSP { get; set; }
        public int? LogInstanc { get; set; }
        public short? UserSign { get; set; }
        public short? UserSign2 { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string PersGroup { get; set; }
        public string JTCode { get; set; }
        public string ExtEmpNo { get; set; }
        public string BirthPlace { get; set; }
        public string PymMeth { get; set; }
        public string ExemptCurr { get; set; }
        public string AddiCurr { get; set; }
        public int? STDCode { get; set; }
        public string FatherName { get; set; }
        public string CPF { get; set; }
        public string CRC { get; set; }
        public string ContResp { get; set; }
        public string RepLegal { get; set; }
        public string DirfDeclar { get; set; }
        public string UF_CRC { get; set; }
        public string IDType { get; set; }
        public string Active { get; set; }
        public int? BPLId { get; set; }
        public string ManualNUM { get; set; }
        public DateTime? PassIssue { get; set; }
        public string PassIssuer { get; set; }
        public string QualCode { get; set; }
        public string PRWebAccss { get; set; }
        public string PrePRWeb { get; set; }
        public string BPLink { get; set; }
    }
}
